### ISSUE TITLE
Run test files

### ISSUE THREAD

**Issue by MonicaSai7** [usnistgov/libbiomeval#2]
How to test the processing of an image when given as input? Is there any set of instructions on how to use the provided cpp files to perform a complete 1:1 matching on images using my own template extractor and matcher?

**Comment by gfiumara** [comment]
There are examples of using `BiometricEvaluation::Image` to decompress common image file formats in [`test_be_image_image.cpp`](https://github.com/usnistgov/libbiomeval/blob/master/src/test/test_be_image_image.cpp). You probably want to use `getRawData()` to get the decompressed bytes to pass to a template extractor.

**Comment by MonicaSai7** [comment]
As far as the .cpp files present, there seems to be no main file that can access all other. So, I'm trying to run the files individually from `libiomeval/src/test`. <br/>
[`test_be_image_image.cpp`](https://github.com/usnistgov/libbiomeval/blob/master/src/test/test_be_image_image.cpp) is throwing the following errors when compiling:<br/>
`test_be_image_image.cpp: In function ‘void compareProperties(std::string, std::shared_ptr<BiometricEvaluation::Image::Image>, std::shared_ptr<BiometricEvaluation::IO::Properties>, std::shared_ptr<BiometricEvaluation::IO::RecordStore>)’:`
`test_be_image_image.cpp:175:6: error: ‘imageType’ was not declared in this scope`
`  175 |  if (imageType != "Raw") {`
`         |      ^~~~~~~~~`
`test_be_image_image.cpp:240:6: error: ‘imageType’ was not declared in this scope`
`  240 |  if (imageType == "Raw") {`
`         |      ^~~~~~~~~`
`test_be_image_image.cpp: In function ‘int main(int, char**)’:`
`test_be_image_image.cpp:357:32: error: ‘imageType’ was not declared in this scope`
 ` 357 |   if (extensions[extension] != imageType)`
`         |                                ^~~~~~~~~`
`test_be_image_image.cpp:366:8: error: ‘imageType’ was not declared in this scope`
`  366 |    if (imageType == "Raw")`
`         |        ^~~~~~~~~`
<br/>Other files are throwing `undefined reference` errors to every namespace and symbol used in the program.
It would be very helpful if any instructions on using the files are provided!
