### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by MonicaSai7** [usnistgov/libbiomeval#3]
Do the test codes and pre-compiled version work on Ubuntu or is it only CentOS/Mac? Due to the difference on SO names between CentOS and Ubuntu, I'm encountering .so files not found w.r.t the exact filenames even after their installation.

**Comment by gfiumara** [comment]
Code should compile well on all platforms, including CentOS, Ubuntu, and macOS. The pre-compiled release posted here on GitHub is CentOS-specific (RPM) and would not work on Ubuntu. It is also lagging quite a bit behind the code in the master branch at this point.
