### ISSUE TITLE
Building in Windows fails

### ISSUE THREAD

**Issue by sifislaz** [usnistgov/libbiomeval#5]
I have cloned the repository on Windows and I have installed the system packages using the vcpkg package manager. Afterwards I added on the root CMakeLists.txt file the following:
```
# SHARED LIBS
set(BUILD_SHARED_LIBS ON)

# vcpkg
set(CMAKE_TOOLCHAIN_FILE "../../vcpkg/scripts/buildsystems/vcpkg.cmake")
set(VCPKG_TARGET_TRIPLET "x64-windows")
```
I have also added a `find_package(packagename REQUIRED)` statement for each package, as stated in the end of the vcpkg install log.
After trial and error some of these statements got replaced by `find_library() and find_path()` statements.
Although, I have issues regarding the package berkeleydb, where the following error occurs:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BERKELEYDB (missing: BERKELEYDB_LIBRARY
  BERKELEYDB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  src/libbiomeval/cmake/Modules/FindBERKELEYDB.cmake:87 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/libbiomeval/CMakeLists.txt:496 (find_package)
```
I have already set these variables on the root folder CMakeLists.txt file.
Any help on how to solve this issue? (The berkeleydb package does not come with a berkeleydb-config.cmake file)

**Comment by gfiumara** [comment]
You need to define the `vcpkg` values before CMake calls to `project()`, which is why the [README specifies](https://github.com/usnistgov/libbiomeval#module-requirements) setting these values on the command-line. Please revert your changes to the `CMakeLists.txt` file and set the variables required on the command-line as specified in the documentation, and it should work. The other build files take care of finding the packages–you should not need to make any alterations.

```
cmake .. -DCMAKE_TOOLCHAIN_FILE=%vcpkg_root%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET="x64-windows" -DBUILD_BIOMEVAL_SHARED=ON
```

**Comment by sifislaz** [comment]
@gfiumara I reverted the changes to the `CMakeLists.txt` and I set the variables required as you stated, but the same error occured. I also noticed that other packages (such as ffmpeg, pcsc, pkgconfig) are not found and even though on the logs seems to find the MPI files, it still builds without MPI support.

**Comment by sifislaz** [comment]
The variable for shared library building is `BUILD_SHARED_LIBS` not `BUILD_BIOMEVAL_SHARED`. When I tried to build the shared library I encountered the same issues as before. The static build was successful though.
