### ISSUE TITLE
Problem trying to complete 'make' command

### ISSUE THREAD

**Issue by jfredyp** [usnistgov/libbiomeval#8]
Hi, I downloaded the source code and tried to run make. However, it fails to complete all the time I get an error related to dependencies using this ::MPI::COMM_WORLD.Get_rank(); I should change it to
    
What is the reason? I'm on MacBook Pro M3
    
Could you help to solve this?

**Comment by gfiumara** [comment]
On macOS, you likely installed the OpenMPI dependency via MacPorts or Homebrew. Homebrew does not include the C++ MPI API. MacPorts does.

**Comment by jfredyp** [comment]
> On macOS, you likely installed the OpenMPI dependency via MacPorts or Homebrew. Homebrew does not include the C++ MPI API. MacPorts does.

Thanks for the recommendation 
I have installed OpenMPI. However the error persists. Maybe another idea?

**Comment by gfiumara** [comment]
The source of your OpenMPI dependency. Did you build from source yourself, install via MacPorts, install via vcpkg, install via Homebrew? You need to be sure your OpenMPI installation includes the C++ MPI API. Please provide this information and the actual error you're receiving. I can build and run just fine on macOS 14.7 with OpenMPI installed via MacPorts.

**Comment by jfredyp** [comment]
> What is the source of your OpenMPI dependency. Did you build from source yourself, install via MacPorts, install via vcpkg, install via Homebrew? You need to be sure your OpenMPI installation includes the C++ MPI API. Please provide this information and the actual error you're receiving. I can build and run just fine on macOS 14.7 with OpenMPI installed via MacPorts.

I'm using hombrew. Even I just to reinstall open-mpi with homebrew. However, the error remains. 

I leave some logs

```

[  8%] Building CXX object lib/CMakeFiles/mpiobjs.dir/be_mpi_resources.cpp.o
/Users/jhonprieto/Documents/Proyectos/PE-RENIEC/libbiomeval/libbiomeval/src/libbiomeval/be_mpi_resources.cpp:51:16: error: no member named 'MPI' in the global namespace; did you mean simply 'MPI'?
   51 |         this->_rank = ::MPI::COMM_WORLD.Get_rank();
      |                       ^~~~~
      |                       MPI
/Users/jhonprieto/Documents/Proyectos/PE-RENIEC/libbiomeval/libbiomeval/src/libbiomeval/../include/be_mpi_runtime.h:20:12: note: 'MPI' declared here
   20 |         namespace MPI {
      |                   ^
/Users/jhonprieto/Documents/Proyectos/PE-RENIEC/libbiomeval/libbiomeval/src/libbiomeval/be_mpi_resources.cpp:51:23: error: no member named 'COMM_WORLD' in namespace 'BiometricEvaluation::MPI'
   51 |         this->_rank = ::MPI::COMM_WORLD.Get_rank();
      |                         ~~~~~^
/Users/jhonprieto/Documents/Proyectos/PE-RENIEC/libbiomeval/libbiomeval/src/libbiomeval/be_mpi_resources.cpp:52:20: error: no member named 'MPI' in the global namespace; did you mean simply 'MPI'?
   52 |         this->_numTasks = ::MPI::COMM_WORLD.Get_size();
      |                           ^~~~~
      |                           MPI
/Users/jhonprieto/Documents/Proyectos/PE-RENIEC/libbiomeval/libbiomeval/src/libbiomeval/../include/be_mpi_runtime.h:20:12: note: 'MPI' declared here
   20 |         namespace MPI {
      |                   ^
/Users/jhonprieto/Documents/Proyectos/PE-RENIEC/libbiomeval/libbiomeval/src/libbiomeval/be_mpi_resources.cpp:52:27: error: no member named 'COMM_WORLD' in namespace 'BiometricEvaluation::MPI'
   52 |         this->_numTasks = ::MPI::COMM_WORLD.Get_size();
      |                             ~~~~~^
4 errors generated.
make[2]: *** [lib/CMakeFiles/mpiobjs.dir/be_mpi_resources.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/mpiobjs.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gfiumara** [comment]
Homebrew's OpenMPI dependency does not include the C++ MPI API. You need to use MacPorts or build it yourself.
